# Generated by Django 3.2.7 on 2021-12-17 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djangoflutterwave', '0003_auto_20211216_1256'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to='profile_images/', verbose_name='Profile Pic')),
                ('gender', models.TextField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], null=True)),
                ('mobile', models.CharField(blank=True, max_length=18, null=True)),
                ('access_plan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_status', to='djangoflutterwave.flwplanmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content_file', models.FileField(upload_to='content_files/')),
                ('content_accessplan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_plan', to='djangoflutterwave.flwplanmodel')),
            ],
        ),
    ]
