# Generated by Django 3.2.7 on 2021-12-16 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoflutterwave', '0003_auto_20211216_1256'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='content_access_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='access_status',
        ),
        migrations.AddField(
            model_name='content',
            name='content_accessplan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_plan', to='djangoflutterwave.flwplanmodel'),
        ),
        migrations.AddField(
            model_name='profile',
            name='access_plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_status', to='djangoflutterwave.flwplanmodel'),
        ),
        migrations.DeleteModel(
            name='AccessPlan',
        ),
    ]
